services:
  - type: web
    name: ecom-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URLS
        sync: false
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_SAME_SITE
        value: None
